---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# data processing
library(data.table)
library(atlastools)
library(sf)

# plotting
library(ggplot2)
library(ggspatial)
library(magick)
library(patchwork)
library(colorspace)
```

```{r}
# get data
data <- fread("data/bat_data.csv")

# filter on SD
data[, SD := sqrt(VARX + VARY + (2 * COVXY))]
data = data[SD < 20, ]

# get summary
data[, c("xround", "yround") := list(round(X, -2), round(Y, -2))]

data_summary = data[, .N, by = c("xround", "yround")]
```

## Read trees and roosts

```{r}
trees = fread("data/trees_update_clusters_Aug2020.csv")
roosts = fread("data/Roosts.csv")
```


```{r}
# fig_heatmap_spatial =
ggplot(data_summary)+
  
  geom_point(
    data = trees,
    aes(X, Y),
    size = 0.05,
    shape = ".",
    col = "seagreen")+
  geom_tile(aes(xround, yround,
                fill = N),
            alpha = 0.8)+
  geom_point(
    data = roosts,
    aes(X, Y,
        shape = "Roost"),
    size = 2,
    stroke = 0.6
  )+
  scale_shape_manual(
    values = c(
      "Roost" = 5
    )
  )+
  scale_fill_viridis_c(
    option = "C",
    breaks = c(10, 100, 1000),
    # labels = c("100", "1K", "10K"),
    trans = "log10",
    direction = -1
  )+
  
  theme_test(base_size = 8)+
  theme(
    legend.position = c(0.9, 0.8),
    legend.key.width = unit(2, units = "mm"),
    legend.key.height = unit(3, units = "mm"),
    axis.title = element_blank(),
    axis.text.y = element_text(
      angle = 90,
      hjust = 0.5
    )
  )+
  coord_sf(crs = 2039,
           xlim = range(data$X),
           ylim = range(data$Y),
           expand = F
  )+
  scale_y_continuous(breaks = c(33.05, 33.10))+
  scale_x_continuous(breaks = c(35.6))+
  annotation_scale(
    bar_cols = c("grey20"),
    height = unit(1, units = "mm"),
    style = "ticks",
    line_width = 1,
    line_col = "grey20",
    text_col = "grey20",
    width_hint = 0.175, 
    location = "br"
  )+
  labs(
    fill = "Fixes",
    shape = NULL
  )
```

```{r}
# save plots
ggsave(
  fig_heatmap_spatial,
  filename = "figures/fig_row_3_eda_bats.png",
  height = 3, width = 2.5
)
```

