---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# data processing
library(data.table)
library(atlastools)
library(sf)

# plotting
library(ggplot2)
library(ggspatial)
library(magick)
library(patchwork)
library(colorspace)
```

```{r}
# get data
data <- fread("data/whole_season_tx_0435.csv")

# convert time to seconds from ms
data[, time := round(TIME / 1000)]

data[, time := as.POSIXct(time, tz = "Amsterdam", origin = "1970-01-01")]
```

## Count over 500m bins

```{r}
# round coord
data_heatmap = copy(data)
data_heatmap[, c("xround", "yround") := list(
  plyr::round_any(X, 100),
  plyr::round_any(Y, 100)
)]

data_heatmap = data_heatmap[, .N, by = c("xround", "yround")]

data_heatmap = data_heatmap[N > 2, ]
```

```{r}
# get griend manual download
st_layers("data/map.osm")
griend = st_read("data/map.osm", layer = "multipolygons")
# merge into one
griend = st_union(griend)

# covnert crs
griend = st_transform(griend, 32631)
```


```{r}
# filter out before specific time
data_filter <- atl_filter_covariates(
  data = data,
  filters = "time > '2018-08-19 18:31:00 Amsterdam'"
)
```

```{r}
# add speed
data_filter[, c(
  "speed_in", "speed_out",
  "angle"
) := list(
  atl_get_speed(data_filter,
    x = "X", y = "Y", time = "time",
    type = "in"
  ),
  atl_get_speed(data_filter,
    x = "X", y = "Y", time = "time",
    type = "out"
  ),
  atl_turning_angle(data_filter, x = "X", y = "Y", time = "time")
)]
```

## remove sd and speed

```{r}
data_filter_sd_speed <- atl_filter_covariates(
  data = data_filter,
  filters = c(
    "SD < 100",
    "((speed_in < 20 & speed_out < 20))"
  )
)
```

## do median smooth

```{r}
data_smooth <- copy(data_filter_sd_speed)

atl_median_smooth(
  data = data_smooth,
  x = "X", y = "Y", time = "TIME", moving_window = 11
)
```

# res patch

```{r}
# require id
data_smooth[, id := "435"]
data_smooth[, TIME := NULL]

# break data for plotting
data_smooth[, seg := cumsum(c(0, diff(time) > (60 * 10)))]

# make small copy
data_for_patch = copy(data_smooth)
data_for_patch = atl_filter_covariates(
  data_for_patch,
  filters = c("time < (time[1] + (18 * 3600))")
)

# set names
setnames(data_smooth, stringr::str_to_lower(colnames(data_smooth)))
setnames(data_for_patch, stringr::str_to_lower(colnames(data_for_patch)))

# get patch
data_patch = atl_res_patch(
  data = data_for_patch
)

# get spatials
data_patch_spatial = atl_patch_summary(data_patch,
                                       which_data = "spatial")

# set crs
st_crs(data_patch_spatial) = 32631

bbox = st_bbox(data_patch_spatial)
```

# make patch

```{r}
bbox_patch = st_bbox(data_patch_spatial[8, ])

fig_patch =
  ggplot()+
  geom_sf(data = data_patch_spatial[8,],
          colour = "grey20",
          size = 0.1,
          alpha = 0.7,
          fill = "lightgrey")+
  geom_path(data = data_smooth[inrange(time,
                                       time[1] + (3600 * 4),
                                       time[1] + (3600 * 12))],
            aes(x, y),
            size = 0.1,
            col = "black")+
  geom_point(data = data_smooth[inrange(time,
                                       time[1] + (3600 * 4),
                                       time[1] + (3600 * 12))],
            aes(x, y),
            size = 0.2,
            shape = 4,
            col = "indianred")+
  coord_sf(
    xlim = c(bbox_patch["xmin"], bbox_patch["xmax"]),
    ylim = c(bbox_patch["ymin"], bbox_patch["ymax"])
  )+
  theme_void()
```

## histogram of speed

### global data

```{r}
# remove silly speeds again
data_smooth[, c(
  "speed_in", "speed_out",
  "angle"
) := list(
  atl_get_speed(data_smooth,
    x = "x", y = "y", time = "time",
    type = "in"
  ),
  atl_get_speed(data_smooth,
    x = "x", y = "y", time = "time",
    type = "out"
  ),
  atl_turning_angle(data_smooth, x = "x", y = "y", time = "time")
)]

# filter speeds
data_smooth <- atl_filter_covariates(
  data = data_smooth,
  filters = c(
    "(speed_in < 20) & (speed_out < 20)"
  )
)
```

### res patch

```{r}
# get points
data_patch_points = atl_patch_summary(
  patch_data = data_patch,
  which_data = "points"
)

# split by patch
data_patch_points = split(data_patch_points, by = "patch")

# get speed
data_patch_points = lapply(data_patch_points, function(df) {
  df[, speed := atl_get_speed(data = df)]
})

# bind
data_patch_points = rbindlist(data_patch_points)
```

### make hist

```{r}
fig_hist = ggplot()+
  geom_histogram(data = data_smooth,
                 aes(x = speed_in, y = ..density..),
               fill = "steelblue",
               # col = "grey",
               bins = 50,
               lwd = 0.1)+
  geom_histogram(data = data_patch_points,
                 aes(x = speed, y = ..density..),
               fill = "indianred",
               # col = "red",
               bins = 50,
               lwd = 0.1)+
  ggthemes::theme_tufte(base_family = "Arial")+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.length = unit(2, units = "mm"),
        plot.background = element_rect(
          fill = alpha("grey95", 0.5),
          colour = NA
        ))+
  scale_x_log10(breaks = c(0.1, 1, 10) / 3.6,
                labels = c(0.1, 1, 10))+
  scale_y_sqrt()+
  coord_cartesian(xlim = c(1e-3, NA))+
  labs(x = "speed (km/hr)")
```


## make overall figure


```{r}
# plot
fig_scales =
  ggplot(data_heatmap)+
  geom_sf(data = griend,
          fill = "grey",
          col = NA)+
  
  geom_tile(aes(xround, yround, fill = N),
            show.legend = F,
            col = "grey",
            size = 0.02,
            alpha = 0.8)+
  # geom_path(data = data_smooth,
  #           aes(x, y,
  #               group = seg),
  #           size = 0.05,
  #           # shape = ".",
  #           alpha = 0.3,
  #           col = "steelblue")+
  geom_path(data = data_smooth[time < time[1] + (3600 * 12) ],
            aes(x, y),
            size = 0.5,
            col = "steelblue")+
  geom_sf(data = data_patch_spatial[1:9,],
          colour = NA,
          # alpha = 0.5,
          fill = "indianred1")+
  annotation_custom(
    grob = ggplotGrob(
      fig_patch
    )
  )+
  annotation_custom(
    grob = ggplotGrob(
      fig_hist
    ),
    xmin = bbox["xmin"] - 1950,
    xmax = bbox["xmin"] - 800,
    ymin = bbox["ymin"] - 300,
    ymax = bbox["ymin"] + 600
  )+
  annotate(
    geom = "segment",
    x = bbox_patch["xmin"],
    xend = bbox_patch["xmin"] - 800,
    y = mean(bbox[c("ymin", "ymax")]),
    yend = mean(bbox[c("ymin", "ymax")]),
    col = "grey50",
    arrow = arrow(angle = 3, type = "closed"),
    size = 0.2
  )+
  scale_fill_continuous_sequential(palette = "Terrain")+
  theme_test(base_family = "Arial")+
  theme(
    panel.background = element_rect(
      # fill = "aliceblue",
      colour = NA
    ),
    axis.title = element_blank(),
    axis.text.y = element_text(
      angle= 90,
      hjust = 0.5
    )
  )+
  scale_y_continuous(breaks = c(53.24, 53.25))+
  coord_sf(xlim = c(bbox["xmin"] - 1800, bbox["xmax"] + 500),
           ylim = c(bbox["ymin"] - 200, bbox["ymax"] + 400))+
  annotation_scale(
    bar_cols = c("grey50"),
    height = unit(1, units = "mm"),
    style = "ticks",
    line_width = 1.5,
    line_col = "grey50",
    text_col = "grey50",
    width_hint = 0.175, 
    location = "br"
  )
```

```{r}
ggsave(
  fig_scales,
  filename = "figures/figure_row_4_f_scales_prelim.png",
  width = 5,
  height = 2.75
)
```

## add red knot

```{r}
# get figure
im <- image_read("figures/figure_row_4_f_scales_prelim.png")

# get red knot
knot <- image_read("figures/knots/knot_poster_picture.png")

# combine knot and figure
im <-
  im %>%
  image_composite(
    image_scale(knot, "50%x"),
    operator = "Atop",
    gravity = "NorthWest",
    offset = "-100-10"
  )

# write
image_write(
  im,
  path = "figures/figure_row_4_f_scales.png"
)
```
