---
  output: html_document
editor_options:
  chunk_output_type: console
---

```{r}
# data processing
library(data.table)
library(atlastools)
library(sf)

# plotting
library(ggplot2)
library(ggspatial)
library(colorspace)
```

```{r}
# get data
data <- fread("data/hald_data/yaps_data-20210223_100929.txt")

# add origin offset
data[, c("x", "y") := list(x + 520440.9, y + 6247193.6)]

# convert time to seconds from ms
data[, time := as.numeric(ts)]
```

```{r}
# get lake
lake <- st_read("data/hald_shore/shore.shp")
```

exploratory plot

```{r}
ggplot(data) +
  geom_path(aes(x, y,
    group = tag,
    col = factor(tag)
  ),
  lwd = 0.2
  )
```

the data are very clean

## split and make residence patches

```{r}
# split
data <- split(data, by = "tag")

# make residence patches and not spatials
patches <- lapply(data, function(df) {
  df[, id := tag]

  patch <- atl_res_patch(df)

  patch <- atl_patch_summary(patch, which_data = "summary")
})

# bind and save
patches_data <- rbindlist(patches)

fwrite(patches_data, file = "data/data_pike_patches.csv")
```


## make overall figure


```{r}
# plot
fig_fish_patch <-
  ggplot() +
  geom_sf(
    data = lake,
    col = "grey20"
  ) +
  geom_path(
    data = patches_data,
    aes(x_median, y_median,
      col = factor(id)
    ),
    show.legend = F,
    size = 0.1
  ) +
  geom_point(
    data = patches_data,
    aes(x_median, y_median,
      size = duration,
      col = factor(id)
    ),
    show.legend = F,
    shape = 19,
    alpha = 0.7
  ) +
  geom_sf(crs = 32632) +
  # size = 0.05,
  # shape = ".",)+
  theme_test(base_family = "Arial") +
  theme(
    axis.title = element_blank(),
    axis.text.y = element_text(
      angle = 90,
      hjust = 0.5
    )
  ) +
  scale_size_area(
    max_size = 8
  ) +
  scale_colour_discrete_sequential(
    palette = "Viridis"
  ) +
  annotation_scale(
    bar_cols = c("grey20"),
    height = unit(1, units = "mm"),
    style = "ticks",
    line_width = 1,
    line_col = "grey20",
    text_col = "grey20",
    width_hint = 0.175,
    location = "br"
  )
```

```{r}
ggsave(
  fig_fish_patch,
  filename = "figures/figure_row_4_pike_patches.png",
  width = 5,
  height = 5
)
```
